######################################################################
# Automatically generated by qmake (2.01a) Di. Apr 18 19:15:36 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . 
INCLUDEPATH += -L"/opt/EVT/eSDK/lib"  -lEmergentCamera  -lEmergentGenICam  -lEmergentGigEVision "/opt/EVT/eSDK/include"

# Input
HEADERS += mainwindow.h stdafx.h targetver.h 
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp stdafx.cpp
